#
# ACCESS_TOKEN - Personal Access Token with "public_repo" permission
# If there is a change to gerefi/gerefi_documentation, this action merges it to gerefi/gerefi/wiki
#
# the opposite merge is implemented as https://github.com/gerefi/gerefi/blob/master/.github/workflows/sync-wiki.yaml
#

name: Sync Wiki2

on:
  push:
    branches:
    - master

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'actions-user' }}

    steps:
    - name: Check out docs repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: gerefi/gerefi.wiki
        persist-credentials: false

    - name: Merge from gerefi_documentation
      run: |
        git remote add technical-git https://github.com/gerefi/gerefi_documentation.git
        git fetch technical-git
        if [ $(git diff technical-git/master | wc -l) -eq 0 ]; then
          echo "skip=true" >> $GITHUB_ENV
          exit 0
        fi
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git merge technical-git/master --allow-unrelated-histories -X theirs

    - name: Push changes gerefi/gerefi wiki
      uses: ad-m/github-push-action@master
      if: ${{ env.skip != 'true' }}
      with:
        repository: gerefi/gerefi.wiki
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
